name: Build and deploy

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: insektionen/songbook-2.0:latest
      - name: Export container
        run: docker save insektionen/songbook-2.0:latest | gzip > songbook-2.0_latest.tar.gz
      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: 'songbook-2.0_latest.tar.gz'
          target: '~/'
      - name: Import and start on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: docker load < songbook-2.0_latest.tar.gz && cd songbook-2.0 && docker-compose up -d
